name: NAME-EXAMINATION UI CI

on:
  pull_request:
    types: [assigned, synchronize, opened, reopened]

defaults:
  run:
    shell: bash

jobs:
  setup-job:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - run: 'true'

  linting:
    needs: setup-job
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [20.5.1]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        working-directory: ./app
        run: |
          npm install
      - name: Linting
        working-directory: ./app
        run: |
          npm run lint

  testing-coverage:
    needs: setup-job
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [20.5.1]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        working-directory: ./app
        run: |
          npm install
      - name: Testing
        working-directory: ./app
        id: test
        run: |
          npm run coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          flags: name-examination-ui
          name: codecov-namex
          fail_ci_if_error: true
          token: c4c60cf0-440a-4527-bdb8-0ae8b51c62bf

  auto-smoke-tests:
    needs: setup-job
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [20.5.1]
        
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies for Application
        working-directory: ./app
        run: npm install

      - name: Install Dependencies for Testing
        working-directory: ./testing
        run: npm install

      - name: Start Application Server and Run Tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./testing
          start: npm run serve-and-smoke
        env:
          CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASEURL }}
          CYPRESS_users: ${{ secrets.CYPRESS_USERS }}
          CYPRESS_ENVIRONMENT: ${{ github.base_ref }}
          CYPRESS_loginproxy: ${{ secrets.CYPRESS_LOGINPROXY }}
          CYPRESS_siteminder: ${{ secrets.CYPRESS_SITEMINDER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload Cypress Videos if Failure
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: ./testing/cypress/videos


  build-check:
    needs: setup-job
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [20.5.1]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        working-directory: ./app
        run: |
          npm install
      - name: build
        working-directory: ./app
        id: build
        run: |
          npm run build


# Add a comment
# Another one